In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.model_selection import KFold,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
filename = "/content/drive/My Drive/College/Data_Mining_Assignments/Classification/wdbc.data" #Arsany
# filename = "/content/drive/My Drive/7th Term Assignments, Sheets & Labs/Classification/wdbc.data" #Yomna
# filename = "/content/drive/My Drive/7th Term Assignments, Sheets & Labs/Classification/wdbc.data" #kirellos

# **Classifier**

In [ ]:
def classifier(P_train, y_train, P_test, y_test): 
  tuned_parameters = [{'C': [0.01, 0.1, 1, 10, 100, 1000]}]
  scores = ['precision', 'recall', 'f1']
  logistic = LogisticRegression()
  for score in scores:
      print("# Tuning hyper-parameters for %s" % score)
      clf = GridSearchCV(logistic, tuned_parameters, cv=5, scoring='%s_macro' % score)
      clf.fit(P_train, y_train)
      print("Best parameter \"C value\"  is " + str(clf.best_params_))
      print()
      print("Grid scores for all C values :")
      print()
      means = clf.cv_results_['mean_test_score']
      stds = clf.cv_results_['std_test_score']
      for mean, std, params in zip(means, stds, clf.cv_results_['params']):
          print("%0.3f (+/-%0.03f) for %r"
                % (mean, std * 2, params))
      print()
      print("Evaluation:")
      print()
      y_true, y_pred = y_test, clf.predict(P_test)
      print(classification_report(y_true, y_pred))
      print("_______________________________________________________________________________________")

# **Preprocessing**



In [ ]:
# reading .data/.csv files
dataframe =  pd.read_csv(filename, header=None)
dataframe.drop(dataframe.columns[0], axis=1, inplace=True)
print("DataFrame is: \n_____________\n\n",dataframe)
data = dataframe.values
data = data.reshape((569,31))
print("\n\nData is: \n________\n\n",data)

# split into inputs and outputs
x, yy = data[:,1:], data[:,0]
y = []
#let the malignint --> 1 and the benign --> 0 in y(output)
for i in yy:
  if i == 'M':
    y.append(1)
  else:
    y.append(0)
y = np.asarray(y)
y = y.reshape(-1, 1)

print("\n X is: \n",x)
print("\n X.shape is:\n", x.shape)
print("\n Y is: \n", y)
print("\n Y.shape is:\n", y.shape)

dataframe.drop(dataframe.columns[0], axis=1, inplace=True)
data = dataframe.values
data = data.reshape((569,30))
print("\n\nData is: \n________\n\n",data)
dataframe

DataFrame is: 
_____________

     1      2      3       4       5   ...       27      28      29      30       31
0    M  17.99  10.38  122.80  1001.0  ...  0.66560  0.7119  0.2654  0.4601  0.11890
1    M  20.57  17.77  132.90  1326.0  ...  0.18660  0.2416  0.1860  0.2750  0.08902
2    M  19.69  21.25  130.00  1203.0  ...  0.42450  0.4504  0.2430  0.3613  0.08758
3    M  11.42  20.38   77.58   386.1  ...  0.86630  0.6869  0.2575  0.6638  0.17300
4    M  20.29  14.34  135.10  1297.0  ...  0.20500  0.4000  0.1625  0.2364  0.07678
..  ..    ...    ...     ...     ...  ...      ...     ...     ...     ...      ...
564  M  21.56  22.39  142.00  1479.0  ...  0.21130  0.4107  0.2216  0.2060  0.07115
565  M  20.13  28.25  131.20  1261.0  ...  0.19220  0.3215  0.1628  0.2572  0.06637
566  M  16.60  28.08  108.30   858.1  ...  0.30940  0.3403  0.1418  0.2218  0.07820
567  M  20.60  29.33  140.10  1265.0  ...  0.86810  0.9387  0.2650  0.4087  0.12400
568  B   7.76  24.54   47.92   181.0  ...  0.

2      3       4       5   ...      28      29      30       31
0    17.99  10.38  122.80  1001.0  ...  0.7119  0.2654  0.4601  0.11890
1    20.57  17.77  132.90  1326.0  ...  0.2416  0.1860  0.2750  0.08902
2    19.69  21.25  130.00  1203.0  ...  0.4504  0.2430  0.3613  0.08758
3    11.42  20.38   77.58   386.1  ...  0.6869  0.2575  0.6638  0.17300
4    20.29  14.34  135.10  1297.0  ...  0.4000  0.1625  0.2364  0.07678
..     ...    ...     ...     ...  ...     ...     ...     ...      ...
564  21.56  22.39  142.00  1479.0  ...  0.4107  0.2216  0.2060  0.07115
565  20.13  28.25  131.20  1261.0  ...  0.3215  0.1628  0.2572  0.06637
566  16.60  28.08  108.30   858.1  ...  0.3403  0.1418  0.2218  0.07820
567  20.60  29.33  140.10  1265.0  ...  0.9387  0.2650  0.4087  0.12400
568   7.76  24.54   47.92   181.0  ...  0.0000  0.0000  0.2871  0.07039

[569 rows x 30 columns]

In [ ]:
#split 80% train and 20%
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.8 )
y_train = y_train.flatten()
y_test = y_test.flatten()
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455,) (114,)


In [ ]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[14.45 20.22 94.49 ... 0.1838 0.4753 0.1013]
 [14.58 21.53 97.41 ... 0.2701 0.4264 0.1275]
 [13.68 16.33 87.76 ... 0.08703999999999999 0.2806 0.07782]
 ...
 [16.11 18.05 105.1 ... 0.1216 0.2792 0.08158]
 [13.85 17.21 88.44 ... 0.051039999999999995 0.2364 0.07182000000000001]
 [12.8 17.46 83.05 ... 0.08296 0.1988 0.07053]]
[1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 0 1 1 0 0
 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0
 0 0 1 1 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 1 1 0 0
 1 0 1 0 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 0 1


**feature normalization on data**

In [ ]:
#min_max_normalization
norm = (dataframe - dataframe.min()) / (dataframe.max() - dataframe.min())* (1-0) + 0
norm

2         3         4   ...        29        30        31
0    0.521037  0.022658  0.545989  ...  0.912027  0.598462  0.418864
1    0.643144  0.272574  0.615783  ...  0.639175  0.233590  0.222878
2    0.601496  0.390260  0.595743  ...  0.835052  0.403706  0.213433
3    0.210090  0.360839  0.233501  ...  0.884880  1.000000  0.773711
4    0.629893  0.156578  0.630986  ...  0.558419  0.157500  0.142595
..        ...       ...       ...  ...       ...       ...       ...
564  0.690000  0.428813  0.678668  ...  0.761512  0.097575  0.105667
565  0.622320  0.626987  0.604036  ...  0.559450  0.198502  0.074315
566  0.455251  0.621238  0.445788  ...  0.487285  0.128721  0.151909
567  0.644564  0.663510  0.665538  ...  0.910653  0.497142  0.452315
568  0.036869  0.501522  0.028540  ...  0.000000  0.257441  0.100682

[569 rows x 30 columns]

In [ ]:
scaler = MinMaxScaler()
scaler.fit(data)
scaled_data = scaler.transform(data)
scaled_data

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

**Feature Normalization on Training and Testing sets**

In [ ]:
# FEATURE NORMALIZATION
scaler = MinMaxScaler()
normalized_X_train = scaler.fit_transform(X_train)
normalized_X_test = scaler.transform(X_test)
print("\n normalized_X_train is:\n____________________\n\n", normalized_X_train)
print("\n normalized_X_test is:\n____________________\n\n", normalized_X_test)

#we do not need it because it is already 0 and 1 scaled
# y_train = scaler.fit_transform(y_train)
# y_test = scaler.transform(y_test)
# print("\n y_train is:\n__________\n\n", y_train)
# print("\n y_test is:\n__________\n\n", y_test)

print("\n\nClassifier after normalization\n______________________________")
classifier(normalized_X_train, y_train, normalized_X_test, y_test)


 normalized_X_train is:
____________________

 [[0.36542884 0.3554278  0.35427294 ... 0.63161512 0.628425   0.30342385]
 [0.37178923 0.39972946 0.37467682 ... 0.92817869 0.53203233 0.4752722 ]
 [0.32775576 0.22387555 0.30724617 ... 0.29910653 0.24462842 0.14941624]
 ...
 [0.44664612 0.28204261 0.42841171 ... 0.41786942 0.24186872 0.17407845]
 [0.33607319 0.25363544 0.31199776 ... 0.17539519 0.15750049 0.11006166]
 [0.28470082 0.26208996 0.27433443 ... 0.28508591 0.08338261 0.10160042]]

 normalized_X_test is:
____________________

 [[1.03375899 0.2962462  1.01118021 ... 0.54810997 0.01636113 0.00137741]
 [0.2176721  0.19208657 0.20452799 ... 0.29127148 0.21900256 0.08271022]
 [0.20739762 0.3432533  0.19670184 ... 0.06948454 0.34042973 0.06677161]
 ...
 [0.2886149  0.28779168 0.28411711 ... 0.3766323  0.20047309 0.22228781]
 [0.48236215 0.32972607 0.4514709  ... 0.28989691 0.18963138 0.03069658]
 [0.22696805 0.28643896 0.22772692 ... 0.48659794 0.21584861 0.24701561]]


Classifier afte

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Best parameter "C value"  is {'C': 100}

Grid scores for all C values :

0.849 (+/-0.022) for {'C': 0.01}
0.949 (+/-0.021) for {'C': 0.1}
0.970 (+/-0.019) for {'C': 1}
0.986 (+/-0.021) for {'C': 10}
0.987 (+/-0.022) for {'C': 100}
0.975 (+/-0.029) for {'C': 1000}

Evaluation:

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

_______________________________________________________________________________________
# Tuning hyper-parameters for recall


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Best parameter "C value"  is {'C': 100}

Grid scores for all C values :

0.635 (+/-0.073) for {'C': 0.01}
0.914 (+/-0.052) for {'C': 0.1}
0.955 (+/-0.017) for {'C': 1}
0.982 (+/-0.028) for {'C': 10}
0.985 (+/-0.025) for {'C': 100}
0.969 (+/-0.037) for {'C': 1000}

Evaluation:

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

_______________________________________________________________________________________
# Tuning hyper-parameters for f1
Best parameter "C value"  is {'C': 100}

Grid scores for all C values :

0.621 (+/-0.100) for {'C': 0.01}
0.927 (+/-0.044) for {'C': 0.1}
0.962 (+/-0.018) for {'C': 1}
0.983 (+/-0.024) for {'C': 10}
0.986 (+/-0.023) for {'C': 100}
0.972 (+/-0.032) for {'C': 1000}

Evaluatio

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
#unused normalization

# from sklearn.preprocessing import Normalizer
# # The normalize features to account for feature scaling
# # Instantiate 
# norm = Normalizer()
# # Fit and Transform both training and testing sets
# X_train_norm = norm.fit_transform(X_train)
# X_test_norm = norm.transform(X_test)
# print("\n X_train_norm is:\n_______________\n\n", X_train_norm)
# print("\n X_test_norm is:\n_______________\n\n", X_test_norm)

**feature selection/projection**(PCA)

In [ ]:
# from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
# # from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
# # Create Decision Tree classifer object
# clf = DecisionTreeClassifier()
# # Train Decision Tree Classifer
# clf = clf.fit(normalized_X_train, y_train)
# #Predict the response for test dataset
# y_pred = clf.predict(normalized_X_test)

In [ ]:
#feature projection using PCA

# PCA algorithm (alpha = 0.95)
def PCA(D, alpha):
  # Compute the mean vector
  mu = np.mean(D, axis = 0)
  print("\n the mean is:\n", mu)

  # center the data
  z = D - mu.T
  print("\n the centered data is:\n",z)

  # compute COV matrix
  COV = np.dot(z.T, z) / D.shape[0]
  print("\n the covariance matrix is:\n",COV)

  # find eigenvalues and eigenvectors
  values, vectors = np.linalg.eigh(COV)
  sorted_eig  = np.argsort(-values)
  values = values[sorted_eig]
  # values = np.diag(values)
  vectors = vectors[:, sorted_eig]
  print("\n the eigenvalues are:\n", values)
  print("\n the eigenvectors are:\n", vectors)

  # fraction of total variance
  tot = np.sum(values)
  var_exp = [(i / tot) for i in (values)]
  # var_exp = np.diag(var_exp)
  print("\n the fraction of total variances:\n", var_exp)

  # calculate the cumulative sum
  fr = np.cumsum(var_exp)
  print("\n the cumulative sum:\n",fr)

  # choose dimentionality
  index = 0
  for i in range(len(fr)):
    if fr[i] >= alpha:
      # smallest r so that f(r) >= alpha
      item_value = fr[i]
      index = i
      break
  print("\n item is:\n",item_value)
  print("\n we take till index: \n", index)

  # Compute projection matrix U
  U = vectors[:, :index]
  print("\n the projection matrix is:\n",U)

  return U

U = PCA(normalized_X_train, 0.95)


 the mean is:
 [0.35018939 0.32110804 0.33726888 0.21659478 0.33593893 0.26035199
 0.20796825 0.24392947 0.37936064 0.26611054 0.11935559 0.18750049
 0.11678805 0.06115854 0.17993827 0.17535701 0.08079853 0.2258976
 0.1773243  0.10050324 0.29631268 0.36062935 0.28259288 0.1696771
 0.40236427 0.218707   0.23126611 0.39436644 0.26141542 0.18943034]

 the centered data is:
 [[ 0.01523945  0.03431976  0.01700406 ...  0.23724868  0.36700957
   0.11399351]
 [ 0.02159984  0.07862141  0.03740794 ...  0.53381225  0.27061691
   0.28584186]
 [-0.02243363 -0.09723249 -0.03002271 ... -0.09525991 -0.016787
  -0.0400141 ]
 ...
 [ 0.09645673 -0.03906543  0.09114283 ...  0.02350297 -0.01954671
  -0.01535189]
 [-0.01411619 -0.0674726  -0.02527112 ... -0.21897125 -0.10391493
  -0.07936868]
 [-0.06548857 -0.05901809 -0.06293445 ... -0.10928053 -0.17803281
  -0.08782992]]

 the covariance matrix is:
 [[ 2.82720123e-02  8.37558260e-03  2.78408060e-02  2.39439130e-02
   3.76687618e-03  1.41509496e-02  2.143

In [ ]:
# Project the training set and test sets
P_train = np.dot(normalized_X_train, U)
print("\n the projection of train is:\n", P_train)
print(P_train.shape)

P_test = np.dot(normalized_X_test, U)
print("\n the projection of test is:\n", P_test)
print(P_test.shape)


 the projection of train is:
 [[-1.52560331e+00 -4.22089760e-01 -1.55896660e-01 ...  5.70334515e-02
   1.22696395e-01  1.60343013e-03]
 [-1.90072326e+00 -6.84639268e-01 -2.20038129e-01 ...  7.82321147e-02
   3.08246422e-02 -4.06833949e-02]
 [-8.47346089e-01 -1.23688034e-01 -4.74958094e-02 ... -5.16677337e-02
   3.42671378e-02 -7.74586543e-03]
 ...
 [-1.41019246e+00 -1.33298250e-01 -2.57159532e-01 ... -7.90567124e-02
   5.25612185e-02 -8.36384973e-03]
 [-7.50832288e-01 -4.06124685e-02 -2.10044132e-01 ... -5.91466681e-02
   1.36396680e-02  2.34762948e-02]
 [-9.07465297e-01 -1.73015062e-01 -3.20311124e-01 ...  6.71929715e-02
   9.34015006e-03 -2.50351083e-04]]
(455, 9)

 the projection of test is:
 [[-2.73230538  0.65312034 -0.33851248 ... -0.5521519   0.26640795
  -0.05933155]
 [-0.74602891 -0.27674974 -0.16394341 ...  0.1123441   0.00306498
  -0.01070598]
 [-0.64540641 -0.43257133 -0.48824819 ...  0.07319151  0.20626567
   0.15504923]
 ...
 [-1.17407878 -0.52655165 -0.19552911 ... -0.1

#**Results** 

In [ ]:
print("\nResults after Projection\n________________________")
classifier(P_train, y_train, P_test, y_test)


Results after Projection
________________________
# Tuning hyper-parameters for precision
Best parameter "C value"  is {'C': 10}

Grid scores for all C values :

0.849 (+/-0.022) for {'C': 0.01}
0.949 (+/-0.021) for {'C': 0.1}
0.974 (+/-0.021) for {'C': 1}
0.981 (+/-0.017) for {'C': 10}
0.980 (+/-0.027) for {'C': 100}
0.977 (+/-0.028) for {'C': 1000}

Evaluation:

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

_______________________________________________________________________________________
# Tuning hyper-parameters for recall
Best parameter "C value"  is {'C': 100}

Grid scores for all C values :

0.635 (+/-0.073) for {'C': 0.01}
0.914 (+/-0.052) for {'C': 0.1}
0.961 (+/-0.026) for {'C': 1}
0.973 (+/-0.